version: 2

jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  build_prestashop17:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Building Prestashop image
          command: docker-compose build prestashop17
      - run:
          name: Saving image
          command: docker save -o ~/prestashop17 project_prestashop17
      - persist_to_workspace:
          root: ~/
          paths:
            - prestashop17
  publish_prestashop17:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Loading image
          command: docker load -i ~/prestashop17
      - run:
          name: Logging into dockerhub
          command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run:
          name: Publishing image
          command: |
            docker tag project_prestashop17 ${DOCKER_USERNAME}/prestashop:1.7
            docker tag project_prestashop17 ${DOCKER_USERNAME}/prestashop:latest
            docker push ${DOCKER_USERNAME}/prestashop:1.7
            docker push ${DOCKER_USERNAME}/prestashop:latest
      - run:
          name: Remove dangling images
          command: docker image prune -a -f

workflows:
  version: 2
  build-and-publish:
    jobs:
      - checkout
      - build_prestashop17:
          requires:
            - checkout
      - publish_prestashop17:
          requires:
            - build_prestashop17
          filters:
            branches:
              only:
                - main
